//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pmsEcommerceEntities1 : DbContext
    {
        private static pmsEcommerceEntities1 instance;
        private pmsEcommerceEntities1()
            : base("name=pmsEcommerceEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static pmsEcommerceEntities1 getInstance()
        {
            if (instance == null)
            {
                instance = new pmsEcommerceEntities1();
            }
            return instance;
        }


        public virtual DbSet<CreateProject> CreateProjects { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<notfication> notfications { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<projectAssign> projectAssigns { get; set; }
        public virtual DbSet<qualification> qualifications { get; set; }
        public virtual DbSet<tbl_Notification> tbl_Notification { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userType> userTypes { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
    }
}
